# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82d2e7c03207fbc0bc02c40185a6aab3b8158f9d1913c3fd4d38723fb2f3b21a7579a661053ebe0df361c1b07daaa917911490782a4bdca642696d806e720120

test:
  secret_key_base: 8c5e10815ee3f70f6c0552b46fbbf8000fddcfdef92bc546b291d42cf7e307e3caa9faa33c7766c4a114bc1e453c587ec15e5f609e6db385dd26cbc09b79eaeb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
